### ISSUE TITLE
11.0-v2: skin don't change automatic for premium players

### ISSUE THREAD

**Issue by xion87** [Th3Tr0LLeR/SkinsRestorer---Maro#16]
hi, premium players when chaning their skin they don't get anymore their skin updated when join my server... i got skinsrestorer installed on bungee side

**Comment by deluxghost** [comment]
same for me

i guess the MCAPI is down now

it always return null:

`[
    {
        "uuid": null,
        "id": null,
        "uuid_formatted": "----",
        "name": null,
        "cache": 1457771677,
        "current_time": 1457771317
    }
]
`

**Comment by Blackfire62** [comment]
If MCAPI is overloaded and MojangAPI does not allow your IP for next 10 minutes, you will get the null exception. You cant bypass it, be patient.

**Comment by Th3Tr0LLeR** [comment]
@xion87 if you are using AutoIn, you will need to enable the autoin option in the config.

**Comment by xion87** [comment]
@Th3Tr0LLeR  I am using bungeeauth... no autoin or stuffs

**Comment by Th3Tr0LLeR** [comment]
Well. I didn't add support for that, or the author didnt add support for
SkinsRestorer. Can't help you right now.

2016-03-12 21:02 GMT+02:00 xion87 <notifications@github.com>:

**Comment by xion87** [comment]
what it mean? skinrestorer was working great before the upgrade to latest revision (1.8-1.9) now my player are complain that when they update their skin on minecraft site, the skin  will never get updated until some admin do /skinsrestorer update nameofplayer nameofplatyer....

**Comment by xion87** [comment]
Also i got this error yesterday, dunno what is
http://hastebin.com/yimatodaka.avrasm

**Comment by Th3Tr0LLeR** [comment]
Nothing on the url.

**Comment by xion87** [comment]
00:42:11 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@5d58c727, id=2936443, owner=skinsrestorer.bungee.SkinsRestorer@71904469, task=skinsrestorer.bungee.SkinFactoryBungee$1@3c7be082, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
	at skinsrestorer.bungee.SkinFactoryBungee$1.run(SkinFactoryBungee.java:51)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xion87** [comment]
player still complaining that skin don't get update automatic, what i should do? ç_ç i have to use autoin?

**Comment by Th3Tr0LLeR** [comment]
Are you using mysql or flat file ?

**Comment by xion87** [comment]
flat

**Comment by Th3Tr0LLeR** [comment]
It should be fixed.

**Comment by xion87** [comment]
Skin still dont' change automatic :(, i changed my skin on minecraft and waited 30 minutes, loiging in my server i still have the old one

**Comment by Th3Tr0LLeR** [comment]
That's why there's the update command.

**Comment by xion87** [comment]
there is no way for done it automatic at login? or in the server with bukkit skin plugin?
